/**
 * Command descriptions — shown when listing employee commands
 * Shared across all tenants. If a command isn't here, the command name is used as-is.
 */

export const COMMAND_LABELS: Record<string, string> = {
  // ── Emlak ──
  portfoyum: "Portföy özeti",
  mulkekle: "Mülk ekle",
  mulkdetay: "Mülk detayı görüntüle",
  mulkduzenle: "Mülk bilgilerini düzenle",
  mulksil: "Mülk sil",
  mulkyonet: "Mülk yönet",
  tara: "Linkten mülk yükle",
  ekle: "Hızlı mülk ekle",
  musterilerim: "Müşteri listesi",
  musteriEkle: "Yeni müşteri ekle",
  musteriDuzenle: "Müşteri bilgisi düzenle",
  eslestir: "Müşteri-mülk eşleştir",
  hatirlatma: "Hatırlatma oluştur",
  takipEt: "Piyasa takibi kur",
  satistavsiye: "Satış tavsiyesi al",
  ortakpazar: "Ortak pazar paylaşımı",
  sunum: "Müşteriye sunum hazırla",
  sunumlarim: "Geçmiş sunumlarım",
  fotograf: "Fotoğraf yükle/düzenle",
  yayinla: "Portala ilan yayınla",
  paylas: "Sosyal medya paylaşımı",
  websitem: "Web sitesi",
  fiyatbelirle: "Fiyat belirle",
  mulkoner: "Bütçeye göre mülk öner",
  rapor: "Haftalık rapor",
  brifing: "Günlük brifing",
  gorevler: "Görev listesi",
  sozlesme: "Yetkilendirme sözleşmesi",
  sozlesmelerim: "Sözleşmelerim",
  hediyeler: "Hediyeler & kampanya",
  webpanel: "Web panel girişi",

  // ── Bayi ──
  ozet: "Günlük özet",
  takvim: "Takvim & ziyaretler",
  kampanyaolustur: "Yeni kampanya oluştur",
  kampanyalar: "Kampanya listesi",
  teklifver: "Bayiye teklif hazırla",
  performans: "Bayi performans analizi",
  segment: "Bayi segmentasyonu",
  siparisolustur: "Yeni sipariş oluştur",
  siparisler: "Sipariş listesi",
  bayidurum: "Bayi durum sorgula",
  ziyaretnotu: "Ziyaret notu ekle",
  ziyaretler: "Ziyaret geçmişi",
  bakiye: "Bayi bakiye sorgula",
  faturalar: "Fatura listesi",
  borcdurum: "Borç durumu",
  ekstre: "Hesap ekstresi",
  odeme: "Ödeme kaydı",
  vadeler: "Vadesi gelen ödemeler",
  tahsilat: "Tahsilat durumu",
  hatirlatgonder: "Tahsilat hatırlatması",
  stok: "Stok durumu",
  kritikstok: "Kritik stok uyarıları",
  stokhareketleri: "Stok hareketleri",
  tedarikciler: "Tedarikçi listesi",
  satinalma: "Satın alma siparişi",
  ihtiyac: "İhtiyaç analizi",
  teslimatlar: "Teslimat planı",
  rota: "Rota optimizasyonu",
  kargotakip: "Kargo takibi",
  urunler: "Ürün kataloğu",
  fiyatliste: "Fiyat listesi",
  yeniurun: "Yeni ürün ekle",
  fiyatguncelle: "Fiyat güncelle",

  // ── Bayi Dealer ──
  siparisver: "Sipariş ver",
  siparislerim: "Siparişlerim",
  tekrarsiparis: "Son siparişi tekrarla",
  bakiyem: "Bakiye durumum",
  faturalarim: "Faturalarım",
  odemelerim: "Ödeme geçmişim",
  fiyatlar: "Fiyat listesi",
  calisanekle: "Çalışan ekle",
  bayidavet: "Bayi davet linki oluştur",
  calisanyonet: "Çalışanları yönet",
  talimat: "Talimat gönder",
  kampanyabildir: "Kampanya bildirimi",
  tahsilatbildir: "Tahsilat hatırlatma",
  aktifkampanyalar: "Aktif kampanyalar",
  mesajgonder: "Firmaya mesaj gönder",

  // ── Muhasebe ──
  fatura_yukle: "Fatura yükle",
  son_faturalar: "Son faturalar",
  fatura_ara: "Fatura ara",
  fatura_detay: "Fatura detayı",
  fatura_rapor: "Fatura raporu",
  mukellefler: "Mükellef listesi",
  mukellef_ekle: "Mükellef ekle",
  yaklasan: "Yaklaşan beyannameler",
  randevular: "Randevu listesi",
  kdv: "KDV hesapla",
  gelir_vergisi: "Gelir vergisi hesapla",
  kurumlar: "Kurumlar vergisi hesapla",
  vergi_raporu: "Vergi raporu",
  kontrol: "Beyanname kontrol",
  oranlar: "Güncel vergi oranları",
  alacaklar: "Alacak takibi",
  geciken: "Geciken ödemeler",
  hatirlatma_gonder: "Tahsilat hatırlatması",
  odeme_ekle: "Ödeme kaydı ekle",
  nakit_akis: "Nakit akış durumu",
  risk: "Risk analizi",

  // ── Otel ──
  misafirler: "Misafir listesi",
  mesajlar: "Gelen mesajlar",
  yanitla: "Mesaj yanıtla",
  eskalasyon: "Eskalasyon",
  rezervasyonlar: "Rezervasyon listesi",
  checkin: "Bugünkü check-in'ler",
  checkout: "Bugünkü check-out'lar",
  musaitlik: "Oda müsaitliği",
  fiyat: "Oda fiyatları",
  rezervasyonekle: "Yeni rezervasyon",
  odalar: "Oda durumu",
  temizlik: "Temizlik görevleri",
  odaguncelle: "Oda durumu güncelle",
  gorevata: "Görev ata",
  faq: "Bilgi bankası",
  odabilgi: "Oda bilgisi",
  tavsiye: "Misafir tavsiyesi",
  yorumlar: "Misafir yorumları",
  durum: "Genel durum özeti",

  // ── Site Yönetim ──
  borcum: "Borç durumu sorgula",
  aidat: "Aidat özeti",
  gelir_gider: "Gelir-gider tablosu",
  duyuru: "Duyuru gönder",
  toplanti: "Toplantı çağrısı",
  mesaj: "Sakin mesajı",
  ariza: "Arıza bildir",
  bakim: "Bakım takibi",
  hukuk: "Hukuki danışma",
  mevzuat: "KMK mevzuatı",
  kayit: "Bina kaydı",
  binakodu: "Bina erişim kodu",

  // ── Market ──
  stokekle: "Stok ekle",
  stokguncelle: "Stok güncelle",
  stoksil: "Stok sil",
  stoksorgula: "Stok sorgula",
  tedarikciekle: "Tedarikçi ekle",
  siparisekle: "Sipariş kalemi ekle",
  siparisdetay: "Sipariş detayı",
  siparisonayla: "Sipariş onayla",
  siparisiptal: "Sipariş iptal",
  fiyatkampanya: "Fiyat kampanyası",
  fiyatsorgula: "Fiyat sorgula",
  satiskaydet: "Satış kaydet",
  raporgunluk: "Günlük rapor",
  raporhaftalik: "Haftalık rapor",
  topsatan: "En çok satanlar",

  sktkontrol: "SKT kontrol",
  sktekle: "SKT ekle",
  kategoriler: "Kategoriler",
  kategoriekle: "Kategori ata",
  kasarapor: "Kasa raporu",
  raporaylik: "Aylık rapor",
  teslimal: "Teslimat al",
};
